package io.eunmin.multiplatform.design.system

import androidx.compose.ui.graphics.Color

val primaryLightHighContrast = Color(0xFF000000)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF1B1B1B)
val onPrimaryContainerLightHighContrast = Color(0xFFD0D0D0)
val secondaryLightHighContrast = Color(0xFF2C2C2C)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF494949)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF000000)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF1B1B1B)
val onTertiaryContainerLightHighContrast = Color(0xFFD0D0D0)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF9F9F9)
val onBackgroundLightHighContrast = Color(0xFF1B1B1B)
val surfaceLightHighContrast = Color(0xFFF9F9F9)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFEBE0E1)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF312B2C)
val outlineVariantLightHighContrast = Color(0xFF4F4749)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF303030)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFC6C6C6)
val surfaceDimLightHighContrast = Color(0xFFB9B9B9)
val surfaceBrightLightHighContrast = Color(0xFFF9F9F9)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF1F1F1)
val surfaceContainerLightHighContrast = Color(0xFFE2E2E2)
val surfaceContainerHighLightHighContrast = Color(0xFFD4D4D4)
val surfaceContainerHighestLightHighContrast = Color(0xFFC6C6C6)

val primaryDarkHighContrast = Color(0xFFF0F0F0)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFC2C2C2)
val onPrimaryContainerDarkHighContrast = Color(0xFF0B0B0B)
val secondaryDarkHighContrast = Color(0xFFF0F0F0)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFC2C2C2)
val onSecondaryContainerDarkHighContrast = Color(0xFF0B0B0B)
val tertiaryDarkHighContrast = Color(0xFFF0F0F0)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFC2C2C2)
val onTertiaryContainerDarkHighContrast = Color(0xFF0B0B0B)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF131313)
val onBackgroundDarkHighContrast = Color(0xFFE2E2E2)
val surfaceDarkHighContrast = Color(0xFF131313)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4C4546)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF9EDEF)
val outlineVariantDarkHighContrast = Color(0xFFCBC0C1)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE2E2E2)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF484848)
val surfaceDimDarkHighContrast = Color(0xFF131313)
val surfaceBrightDarkHighContrast = Color(0xFF505050)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1F1F1F)
val surfaceContainerDarkHighContrast = Color(0xFF303030)
val surfaceContainerHighDarkHighContrast = Color(0xFF3B3B3B)
val surfaceContainerHighestDarkHighContrast = Color(0xFF474747)







